apiVersion: ingressapp.app.io/v1
kind: App
metadata:
  name: app-sample
spec:
  enable_ingress: true
  enable_service: true
  env:
  - name: DB_SOURCE
    value: postgresql://root:secret@engine-postgres/simple_bank?sslmode=disable
  image: csdengh/simplebank:29c6f0f910f70f8361fb0afa969f47b3f3d84ddc
  port:
  - 8090
  - 8190
  replicas: 2
