# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      image:
        required: true
        description: 'docker image name'
      sha-tag:
        required: true
        description: 'docker image tag'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Set up Go
        uses: actions/setup-go@v3
        # if: ${{ github.event.inputs.image }}
        with:
          go-version: 1.17
      
      - name: Check out code into the Go module directory
        # if: ${{ github.event.inputs.image }}
        uses: actions/checkout@v3

      - name: manifest edit
        # if: ${{ github.event.inputs.image }}
        run: |
          IMAGE=${{ github.event.inputs.image }}:${{ github.event.inputs.sha-tag }} ./main
      - name: safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v2
        # if: ${{ github.event.inputs.image }}
        with:
          message: "cd set image to ${{ github.event.inputs.image }}:${{ github.event.inputs.sha-tag }}"